// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-properties.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function dbError(message) {
  return {
    content: [{ type: "text", text: `Database error: ${message}` }],
    isError: true
  };
}

// src/lib/mcp/tools/list-properties.ts
var list_properties_default = defineTool({
  name: "list_properties",
  title: "List properties",
  description: "List all properties owned by the signed-in landlord.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("properties").select("id, name, address, created_at").order("created_at", { ascending: false });
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-houses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_houses_default = defineTool2({
  name: "list_houses",
  title: "List houses",
  description: "List houses (rental units) owned by the signed-in landlord, optionally filtered by property_id.",
  inputSchema: {
    property_id: z.string().uuid().optional().describe("Filter to a single property")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("houses").select("id, house_number, rent_amount, deposit, property_id, created_at").order("house_number");
    if (property_id) query = query.eq("property_id", property_id);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { houses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tenants.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_tenants_default = defineTool3({
  name: "list_tenants",
  title: "List tenants",
  description: "List tenants belonging to the signed-in landlord.",
  inputSchema: {
    search: z2.string().trim().min(1).optional().describe("Filter by name substring")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("tenants").select("id, full_name, phone, house_id, created_at").order("full_name");
    if (search) query = query.ilike("full_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tenants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_payments_default = defineTool4({
  name: "list_payments",
  title: "List recent payments",
  description: "List the most recent rent payments recorded for the signed-in landlord.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows (default 50)"),
    tenant_id: z3.string().uuid().optional().describe("Filter to one tenant")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, tenant_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("payments").select("id, amount, payment_date, mpesa_reference, tenant_id, house_id, source, created_at").order("payment_date", { ascending: false }).limit(limit ?? 50);
    if (tenant_id) query = query.eq("tenant_id", tenant_id);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { payments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hnzvcvuaorupbvkaxzya";
var mcp_default = defineMcp({
  name: "kodi-pap-mcp",
  title: "KODI PAP",
  version: "0.1.0",
  instructions: "Read-only access to a KODI PAP landlord's properties, houses, tenants, and rent payments. All tools act as the signed-in landlord and are scoped by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_properties_default,
    list_houses_default,
    list_tenants_default,
    list_payments_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
