-- Fix a bypass in protect_inbound_email(): its "legitimate auto-generation"
-- case was inferred from OLD/NEW state shape (OLD.inbound_email IS NULL and
-- account_status transitioning to 'active'), not from whether the
-- generation trigger actually ran. A landlord could bundle both fields into
-- one request — e.g. PATCH { account_status: 'active', inbound_email:
-- 'squatted@kodipap.com' } on their own still-pending row — and the guard
-- would see the same state shape as a legitimate activation and let it
-- through with an attacker-controlled value, since generate_inbound_email()
-- never overwrites a NEW.inbound_email that's already non-null.
--
-- Fix: generate_inbound_email() now sets a transaction-local flag when it
-- actually runs and actually generates a value. protect_inbound_email()
-- checks that flag instead of re-deriving intent from OLD/NEW shape. If the
-- attacker's request already carries a non-null inbound_email, the
-- generation trigger's own WHEN clause (NEW.inbound_email IS NULL) never
-- fires, the flag is never set, and the guard correctly rejects the write.

CREATE OR REPLACE FUNCTION public.generate_inbound_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  base_slug TEXT;
  candidate TEXT;
  suffix INT := 1;
BEGIN
  base_slug := lower(regexp_replace(coalesce(NEW.full_name, ''), '[^a-zA-Z0-9\s]', '', 'g'));
  base_slug := regexp_replace(trim(base_slug), '\s+', '.', 'g');

  IF base_slug = '' THEN
    base_slug := 'landlord';
  END IF;

  candidate := base_slug || '@kodipap.com';

  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE inbound_email = candidate) LOOP
    suffix := suffix + 1;
    candidate := base_slug || suffix::text || '@kodipap.com';
  END LOOP;

  NEW.inbound_email := candidate;
  PERFORM set_config('app.inbound_email_autogenerated', 'true', true);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.protect_inbound_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- No-op fast path: most updates to profiles don't touch this column.
  IF NEW.inbound_email IS NOT DISTINCT FROM OLD.inbound_email THEN
    RETURN NEW;
  END IF;

  -- Case 1: the generation trigger actually ran and produced this value for
  -- THIS row. The flag is transaction-local, not row-local, so it's reset
  -- immediately after being consumed — otherwise a multi-row UPDATE where
  -- an earlier row legitimately generates would leave the flag set for a
  -- later row in the same statement that didn't go through generation.
  IF current_setting('app.inbound_email_autogenerated', true) = 'true' THEN
    PERFORM set_config('app.inbound_email_autogenerated', 'false', true);
    RETURN NEW;
  END IF;

  -- Case 2: acting user is a super admin.
  IF auth.uid() IS NOT NULL AND public.has_role(auth.uid(), 'SUPER_ADMIN') THEN
    RETURN NEW;
  END IF;

  -- Case 3: backend/service-role operations have no authenticated user.
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'inbound_email can only be set by the system or a super admin';
END;
$$;
