ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS inbound_email TEXT UNIQUE;

CREATE OR REPLACE FUNCTION public.generate_inbound_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  base_slug TEXT;
  candidate TEXT;
  suffix INT := 1;
BEGIN
  base_slug := lower(regexp_replace(coalesce(NEW.full_name, ''), '[^a-zA-Z0-9\s]', '', 'g'));
  base_slug := regexp_replace(trim(base_slug), '\s+', '.', 'g');

  IF base_slug = '' THEN
    base_slug := 'landlord';
  END IF;

  candidate := base_slug || '@kodipap.com';

  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE inbound_email = candidate) LOOP
    suffix := suffix + 1;
    candidate := base_slug || suffix::text || '@kodipap.com';
  END LOOP;

  NEW.inbound_email := candidate;
  PERFORM set_config('app.inbound_email_autogenerated', 'true', true);
  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.generate_inbound_email() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.protect_inbound_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NEW.inbound_email IS NOT DISTINCT FROM OLD.inbound_email THEN
    RETURN NEW;
  END IF;

  IF current_setting('app.inbound_email_autogenerated', true) = 'true' THEN
    PERFORM set_config('app.inbound_email_autogenerated', 'false', true);
    RETURN NEW;
  END IF;

  IF auth.uid() IS NOT NULL AND public.has_role(auth.uid(), 'SUPER_ADMIN') THEN
    RETURN NEW;
  END IF;

  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'inbound_email can only be set by the system or a super admin';
END;
$$;

REVOKE EXECUTE ON FUNCTION public.protect_inbound_email() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS generate_inbound_email_trigger ON public.profiles;
CREATE TRIGGER generate_inbound_email_trigger
BEFORE UPDATE ON public.profiles
FOR EACH ROW
WHEN (
  OLD.account_status IS DISTINCT FROM 'active'
  AND NEW.account_status = 'active'
  AND NEW.inbound_email IS NULL
)
EXECUTE FUNCTION public.generate_inbound_email();

DROP TRIGGER IF EXISTS zz_protect_inbound_email_trigger ON public.profiles;
CREATE TRIGGER zz_protect_inbound_email_trigger
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.protect_inbound_email();