-- Guard against direct/unauthorized writes to profiles.inbound_email.
--
-- profiles.inbound_email is meant to be:
--   1. Auto-generated by generate_inbound_email() when a landlord's account
--      transitions to 'active' (only while it is still NULL), or
--   2. Edited afterwards only by a SUPER_ADMIN via the admin UI, or
--   3. Written by backend/service-role operations (migrations, edge
--      functions) which have no authenticated user context.
--
-- The existing RLS policy ("Users can update their own profile") has no
-- column-level restriction, so without this guard any landlord could set
-- their own inbound_email directly via the client SDK, bypassing the
-- super-admin-only invariant and potentially squatting on an address that
-- would otherwise be auto-generated for another landlord.
CREATE OR REPLACE FUNCTION public.protect_inbound_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- No-op fast path: most updates to profiles don't touch this column.
  IF NEW.inbound_email IS NOT DISTINCT FROM OLD.inbound_email THEN
    RETURN NEW;
  END IF;

  -- Case 1: legitimate auto-generation on account activation.
  -- Checked against OLD (not NEW) so this is correct regardless of
  -- trigger firing order relative to generate_inbound_email_trigger.
  IF OLD.inbound_email IS NULL
     AND OLD.account_status IS DISTINCT FROM 'active'
     AND NEW.account_status = 'active' THEN
    RETURN NEW;
  END IF;

  -- Case 2: acting user is a super admin.
  IF auth.uid() IS NOT NULL AND public.has_role(auth.uid(), 'SUPER_ADMIN') THEN
    RETURN NEW;
  END IF;

  -- Case 3: backend/service-role operations have no authenticated user.
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'inbound_email can only be set by the system or a super admin';
END;
$$;

-- Named to sort after "generate_inbound_email_trigger" (Postgres fires
-- same-timing BEFORE UPDATE triggers on a table in alphabetical order by
-- trigger name), so this guard sees the already-generated NEW.inbound_email
-- from the generation trigger on the same activation UPDATE.
CREATE TRIGGER zz_protect_inbound_email_trigger
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.protect_inbound_email();
